midi:
  input_port: "UM-One"
  output_port: "UM-One"
  apps: 
    - name: "qlc"
      output_port: "qlc-in"
      input_port: "qlc-out"
    - name: "voicemeeter"
      output_port: "xtouch-gw"
      input_port: "xtouch-gw-feedback"

xtouch:
  mode: "mcu"  # "mcu" (par défaut) ou "ctrl"
  overlay_per_app:
    qlc:
      mode: "8bit"
    voicemeeter:
      mode: "percent"

obs:
  host: "127.0.0.1"
  port: 4455
  password: "aaaaaa"

paging:
  channel: 1
  prev_note: 46
  next_note: 47

pages_global:
  controls:
    vpot6_rotate: { app: "obs", action: "nudgeX", params: ["--- CAM Main 2", "--- CAM Main", 1] }
    vpot7_rotate: { app: "obs", action: "nudgeY", params: ["--- CAM Main 2", "--- CAM Main", 1] }
    vpot8_rotate: { app: "obs", action: "scaleUniform", params: ["--- CAM Main 2", "--- CAM Main", 0.02] }

    fader_master:
      app: "qlc"
      midi: { type: "cc", channel: 1, cc: 78 }

    assign_track:
      app: "obs"
      action: "changeScene"
      params: ["--- CAM Main"]
      indicator: { signal: "obs.selectedScene", equals: "--- CAM Main" }

    assign_pan:
      app: "obs"
      action: "changeScene"
      params: ["--- CAM Main 2"]
      indicator: { signal: "obs.selectedScene", equals: "--- CAM Main 2" }

    assign_eq:
      app: "obs"
      action: "changeScene"
      params: ["--- CAM Jardin"]
      indicator: { signal: "obs.selectedScene", equals: "--- CAM Jardin" }

    assign_send:
      app: "obs"
      action: "changeScene"
      params: ["--- CAM Cour"]
      indicator: { signal: "obs.selectedScene", equals: "--- CAM Cour" }

    assign_plugin:
      app: "obs"
      action: "changeScene"
      params: ["--- Blur"]
      indicator: { signal: "obs.selectedScene", equals: "--- Blur" }

    global_view:
      app: "obs"
      action: "toggleStudioMode"
      indicator: { signal: "obs.studioMode", truthy: true }

    play:
      app: "obs"
      action: "TriggerStudioModeTransition"
      indicator: { signal: "obs.studioMode", truthy: true }

pages:
  - name: "Voicemeeter+QLC"
    lcd:
      labels:
        - "Mic\nBaba"
        - "Mic\nMath"
        - "Mic\nJu"
        - "Son\nMac"
        - "Son\nPC"
        - "Son\nMASTER"
        - "Son\nRetours"
        - "Lum\nFace"
      colors: [1,1,1,4,4,7,5,3]
    controls:
      fader1:
        app: "voicemeeter"
        midi: {type: "passthrough"}
      fader2:
        app: "voicemeeter"
        midi: {type: "passthrough"}
      fader3:
        app: "voicemeeter"
        midi: {type: "passthrough"}
      fader4:
        app: "voicemeeter"
        midi: {type: "passthrough"}
      fader5:
        app: "voicemeeter"
        midi: {type: "passthrough"}
      fader6:
        app: "voicemeeter"
        midi: {type: "passthrough"}
      fader7:
        app: "voicemeeter"
        midi: {type: "passthrough"}
      fader8:
        app: "qlc "
        midi: {type: "cc", channel: 1, cc: 77}
        overlay:
          mode: "8bit"
      mute1:
        app: "voicemeeter"
        midi: {type: "passthrough"}
      mute2:
        app: "voicemeeter"
        midi: {type: "passthrough"}
      mute3:
        app: "voicemeeter"
        midi: {type: "passthrough"}
        
  - name: "Lum contres"
    lcd:
      labels:
        - "Lat Jar\nDimmer"
        - "Lat Jar\nRouge"
        - "Lat Jar\nVert"
        - "Lat Jar\nBleu"
        - "Lat Cour\nDimmer"
        - "Lat Cour\nRouge"
        - "Lat Cour\nVert"
        - "Lat Cour\nBleu"
      colors: [7,1,2,4,7,1,2,4]
    controls:
      fader1:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 81 }
      fader2:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 82 }
      fader3:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 83 }
      fader4:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 84 }
      fader5:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 85 }
      fader6:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 86 }
      fader7:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 87 }
      fader8:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 88 }
      
      # Boutons couleur Frame 3 (Lum Contres)
      mod_shift:      # Orange
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 40 }  # CC 40
      mod_option:     # Blanc
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 41 }  # CC 41
      auto_read_off:  # Bleu
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 42 }  # CC 42
      auto_write:     # Cyan
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 47 }  # CC 47
      mod_control:    # Jaune
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 43 }  # CC 43
      mod_cmd_alt:    # Roses
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 44 }  # CC 44
      auto_touch:     # Rouge
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 45 }  # CC 45
      auto_latch:     # Vert
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 70 }  # CC 46
  - name: "Néons Latéraux RGB"
    lcd:
      labels:
        - "Jardin\nRouge"
        - "Jardin\nVert"
        - "Jardin\nBleu"
        - "Cours\nRouge"
        - "Cours\nVert"
        - "Cours\nBleu"
        - "-"
        - "-"
      colors: [1,2,4,1,2,4,0,0]
    controls:
      fader1:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 90 }
      fader2:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 91 }
      fader3:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 92 }
      fader4:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 93 }
      fader5:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 94 }
      fader6:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 95 }
      
      # Boutons couleur Frame 2 (Néons Latéraux)
      mod_shift:      # Orange
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 32 }  # CC 32
      mod_option:     # Blanc
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 33 }  # CC 33
      auto_read_off:  # Bleu
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 34 }  # CC 34
      auto_write:     # Cyan
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 39 }  # CC 39
      mod_control:    # Jaune
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 35 }  # CC 35
      mod_cmd_alt:    # Roses
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 36 }  # CC 36
      auto_touch:     # Rouge
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 37 }  # CC 37
      auto_latch:     # Vert
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 38 }  # CC 38

  - name: "Néons Contres RGB"
    lcd:
      labels:
        - "Contre J\nRouge"
        - "Contre J\nVert"
        - "Contre J\nBleu"
        - "Contre C\nRouge"
        - "Contre C\nVert"
        - "Contre C\nBleu"
      colors: [1,2,4,1,2,4,0,0]
    controls:
      fader1:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 96 }
      fader2:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 97 }
      fader3:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 98 }
      fader4:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 99 }
      fader5:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 100 }
      fader6:
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 101 }
      
      # Boutons couleur Frame 1 (Néons Contres)
      mod_shift:      # Orange
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 24 }  # CC 24
      mod_option:     # Blanc
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 25 }  # CC 25
      auto_read_off:  # Bleu
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 26 }  # CC 26
      auto_write:     # Cyan
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 31 }  # CC 31
      mod_control:    # Jaune
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 27 }  # CC 27
      mod_cmd_alt:    # Roses
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 28 }  # CC 28
      auto_touch:     # Rouge
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 29 }  # CC 29
      auto_latch:     # Vert
        app: "qlc"
        midi: { type: "cc", channel: 1, cc: 30 }  # CC 30
    passthroughs:
      - driver: "midi"
        to_port: "qlc-in"
        from_port: "qlc-out"
        transform:
          pb_to_cc:
            target_channel: 1   # P4 = même CC que P2 mais sur canal MIDI 2 (QLC+ = +128)
            base_cc: 96     # Base CC P2 (80) → P4 = 209–216 en QLC
            cc_by_channel:
              9: 78  # Master Dimmer (Fader 9)