midi:
  input_port: "UM-One"
  output_port: "UM-One"

paging:
  channel: 1
  prev_note: 46
  next_note: 47

pages:
  - name: "Voicemeeter Main"
    passthrough:
      driver: "midi"
      to_port: "xtouch-gw"
      from_port: "xtouch-gw-feedback"
    controls: {}
  - name: "QLC+"
    passthrough:
      driver: "qlc"
      to_port: "qlc-in"
      from_port: "qlc-out"
  - name: "Default"
    controls: {} 